name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: manchalsharma08/my-nginx-app:latest, manchalsharma08/my-nginx-app:${{ github.sha }}
  expose: 
    runs-on: ubuntu-latest

    steps:
    - name: Expose Docker image to browser
      run: |
        echo "Expose Docker image to browser"
        echo "Docker image exposed successfully"  
        docker run -d -p 80:80 manchalsharma08/my-nginx-app:latest
        echo "Docker image is running on http://localhost:80"
        echo "You can access the Docker image in your browser at http://localhost:80" 
